// <auto-generated />
namespace database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addTitle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTitle));
        
        string IMigrationMetadata.Id
        {
            get { return "201710232110401_addTitle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
